/* eslint-disable react-hooks/exhaustive-deps */
import React, { useEffect, useState } from 'react';
import type { GetStaticProps, NextPage } from 'next';
import type { FieldSet } from 'airtable';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';
import { StationListBox } from '../components/StationListBox';
import { TimeTable } from '../components/TimeTable';
import Navbar from '../components/Navbar';

const Home: NextPage = ({ stationData, timeTableData, busData }) => {
  const [selectedStationFrom, setSelectedStationFrom] = useState<
    FieldSet | undefined
  >();
  const [selectedStationTo, setSelectedStationTo] = useState<
    FieldSet | undefined
  >();

  useEffect(() => {
    setSelectedStationFrom(stationData[0]);
    setSelectedStationTo(stationData[1]);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <h1 className={styles.title}>バス時刻表</h1>
        <StationListBox
          label='出発地：'
          stations={stationData}
          selected={selectedStationFrom}
          setSelected={setSelectedStationFrom}
        />
        <StationListBox
          label='行き先：'
          stations={stationData}
          selected={selectedStationTo}
          setSelected={setSelectedStationTo}
        />
        <TimeTable
          busTable={busData}
          timeTableTable={timeTableData}
          from={selectedStationFrom}
          to={selectedStationTo}
        />
      </main>
      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  try {
    const res_station = await fetch('http://localhost:3000/api/getStation');
    const res_time_table = await fetch(
      'http://localhost:3000/api/getTimeTable'
    );
    const res_bus = await fetch('http://localhost:3000/api/getBus');
    return {
      props: {
        stationData: await res_station.json(),
        timeTableData: await res_time_table.json(),
        busData: await res_bus.json(),
      },
    };
  } catch (err) {
    console.error(err);
    return {
      props: {
        err: 'データ取得で問題が発生しました。',
      },
    };
  }
};

export default Home;
