/* eslint-disable react-hooks/exhaustive-deps */
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Airtable from 'airtable';
import React, { useCallback, useEffect, useState } from 'react';

const Home: NextPage = () => {
  type Fieldset = {
    id: string;
    name: string;
  };
  const [stations, setStations] = useState<Fieldset[]>([]);
  const formattedRecords: Fieldset[] = [];
  const getTimeTable = useCallback(async () => {
    const base = new Airtable({
      apiKey: process.env.NEXT_PUBLIC_AIRTABLE_API_KEY,
    }).base(process.env.NEXT_PUBLIC_AIRTABLE_BASE_ID as string);

    base('Station')
      .select()
      .eachPage(
        function page(records, fetchNextPage) {
          records.forEach(function (record) {
            console.log(`Name: ${record.get('Name')} Id: ${record.id}`);
            formattedRecords.push({
              id: record.get('Id') as string,
              name: record.get('Name') as string,
            });
          });
          fetchNextPage();
        },
        function done(err) {
          if (err) {
            console.error(err);
            return;
          }
          setStations(formattedRecords);
        }
      );
  }, []);

  useEffect(() => {
    getTimeTable();
    console.table(stations);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>
        <ol>
          {stations.map((station) => (
            <li key={station.id}>{station.name}</li>
          ))}
        </ol>
      </main>
      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
